[modules]
autoload=no

; PBX / dialplan
load => pbx_config.so

; PJSIP core dependencies
load => res_pjproject.so
load => res_sorcery_memory.so
load => res_sorcery_config.so
load => res_sorcery_astdb.so

; PJSIP
load => res_pjsip.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_anonymous.so
load => res_pjsip_endpoint_identifier_ip.so
load => res_pjsip_endpoint_identifier_user.so
load => res_pjsip_pubsub.so
load => res_pjsip_session.so
load => chan_pjsip.so

; RTP
load => res_rtp_asterisk.so

; Codecs
load => codec_alaw.so
load => codec_ulaw.so
load => codec_g722.so

; Echo test
load => app_echo.so

; Explicitly disabled unused modules
noload => chan_unistim.so
noload => res_stun_monitor.so
